[project]
name = "echomind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.12.49",
    "llama-index-embeddings-gemini>=0.3.2",
    "llama-index-llms-gemini>=0.5.0",
    "python-dotenv>=1.1.1",
]
